### ISSUE TITLE
Badge in segment bar.

### ISSUE THREAD

**Issue by shoaibmushtaq** [Karthik-B-06/react-native-segmented-control#13]
Please add badge support.

**Comment by Karthik-B-06** [comment]
@shoaibmushtaq Can you add a screenshot of what you are expecting?

**Comment by alpesht-nimblechapps** [comment]
Please provide support to change borderRadius

**Comment by jvt** [comment]
@alpesht-nimblechapps This can be accomplished with the `containerStyle` and `tileStyle` props already by setting a `borderRadius` value in there.
![IMG_4040](https://user-images.githubusercontent.com/2718101/122653962-50cc8b00-d116-11eb-9b03-740d0fe160a9.jpg)
