### ISSUE TITLE
Show information according to the tabs that have been selected

### ISSUE THREAD

**Issue by Bladymendoza97** [Karthik-B-06/react-native-segmented-control#24]
I am trying to be able to show some information according to the tabs that I choose, for example, I want to touch tab 1, then I would like it to show something inside there, and if you press tab 2 in the same way I want to show something

**Comment by Bladymendoza97** [comment]
I only need to display two images based on the tab I am playing

https://user-images.githubusercontent.com/41081923/120372638-aad6ef00-c2d4-11eb-92d1-86297fe384f0.mov

**Comment by Karthik-B-06** [comment]
Hey @Bladymendoza97, You will be storing the current selected tab in a state variable right ? Isn't that info enough to manipulate the information you want to show ? https://user-images.githubusercontent.com/35562287/120377303-962d4200-c33a-11eb-88e8-18034aa6dea2.mp4

Here the information below is based on the Tab Selected.

**Comment by Bladymendoza97** [comment]
This is my current function component, when I click on tab1 I would like to move into that tab a 1, as shown in the video, can you help me?

`export const TaskScreen = () => {
    const [tabIndex, setTabIndex] = useState(1);
    const [theme, setTheme] = useState("LIGHT");
    const toggleTheme = () =>
        theme === "LIGHT" ? setTheme("DARK") : setTheme("LIGHT");
    const handleTabsChange = (index: any) => {
        setTabIndex(index);

    }
    return (

        <SafeAreaView>
            <ScrollView>
                <View
                    style={[
                        styles.container,
                        { backgroundColor: theme === "LIGHT" ? "white" : "black" },
                    ]}
                >
                    <Text
                        style={[
                            styles.textStyle,
                            { color: theme === "LIGHT" ? "black" : "white" },
                        ]}
                    >
                        Hello,World !
                  </Text>
                    <Button title="Toggle Theme" onPress={toggleTheme} />


                    <Text
                        style={[
                            styles.textStyle,
                            { color: theme === "LIGHT" ? "black" : "white" },
                        ]}
                    >
                        Segmented Control with 2 labels
                                </Text>
                    <SegmentedControl
                        tabs={["Tab 1", "Tab 2"]}
                        // onChange={() => { }}
                        paddingVertical={6}
                        containerStyle={{
                            marginVertical: 20,
                        }}
                        currentIndex={tabIndex}
                        onChange={handleTabsChange}
                        theme={theme}
                        
                    />
                </View>
            </ScrollView>
        </SafeAreaView>

    )

}`

**Comment by Bladymendoza97** [comment]
How do I store the selected tab in a state variable?

**Comment by Karthik-B-06** [comment]
Okay, where is the code related to images ? 
And the currently selected tab is stored in the variable tabIndex. Based on this value you will have to write a conditional render.

**Comment by Bladymendoza97** [comment]
This is my code based on the images: 

`                    <View >

                    <View> <Image source={require('../assets/ImageParentMain.png')}/></View>

                    <View> <Image source={require('../assets/ImageParentMain.png')}/></View>

                    </View>`

**Comment by Bladymendoza97** [comment]
I can think of something like this to show the images, according to the selected tab:

{(tabIndex === 0)? image1 : image2}

**Comment by Bladymendoza97** [comment]
What do you think? You can help?

**Comment by Bladymendoza97** [comment]
Hey?

**Comment by Karthik-B-06** [comment]
Hey man, you will have to try something like this :

```
{ 
   tabIndex === 0 ?  
   <View> <Image source={require('../assets/ImageParentMain.png')}/></View> :
  <View> <Image source={require('../assets/ImageParentMain.png')}/></View> 
}

```

**Comment by Bladymendoza97** [comment]
Thank you very much friend, I had achieved it just before this message, I thank you very much for your help and for this incredible library

**Comment by Karthik-B-06** [comment]
Great and Thank you !! @Bladymendoza97
