### ISSUE TITLE
README broken image links

### ISSUE THREAD

**Issue by juanAFernandez** [Karthik-B-06/react-native-segmented-control#27]
As example app has been removed in [297943bd4e6d1937274f86471838d349ec1e0e86](https://github.com/Karthik-B-06/react-native-segmented-control/commit/297943bd4e6d1937274f86471838d349ec1e0e86) commit the images linked in the README.md are broken. 
![imagen](https://user-images.githubusercontent.com/5589299/148212634-5271238c-6c0b-4119-be6a-8a2644739025.png)

**Comment by Karthik-B-06** [comment]
Hey yes. Was working on a newer better version of the same. Which now will be available. Thanks :)
