### ISSUE TITLE
Segmented control not rendering correctly

### ISSUE THREAD

**Issue by relez** [Karthik-B-06/react-native-segmented-control#36]
Hi there, I am trying to use this awesome plugin but looks like something is wrong, the control is not being rendered correctly or I am missing something.

According to the documentation, I have installed the required packages like:

```
...
"react-native-gesture-handler": "~2.1.0",
"react-native-reanimated": "~2.3.1"
...
```
Inside my view, I have:

```
<SegmentedControl
  containerMargin={16}
  segments={['Label 1', 'Label 2']}
  onChange={(index) => setTabIndex(index)}
  currentIndex={tabIndex}
/>
```
But this is what I got:
![simulator_screenshot_A22A007A-43FB-49F3-A7AF-C9CD9F630B1C](https://user-images.githubusercontent.com/3420851/156239518-31434c93-30d2-4ba2-898c-2564a618ab63.png)

**Comment by Karthik-B-06** [comment]
Hey @relez were you able to fix the issue ?
