### ISSUE TITLE
[Feature request] Add support for RTL phones

### ISSUE THREAD

**Issue by nadav2051** [Karthik-B-06/react-native-segmented-control#4]
If the phone is currently set to RTL, the sliding direction will not change and it will cause the toggle to slide off screen

![image](https://user-images.githubusercontent.com/6547468/87874030-15d64a80-c9cf-11ea-9421-169bbfe1bfc3.png)

**Comment by Karthik-B-06** [comment]
Great fix, Can I have a working demo after the fix?

**Comment by nadav2051** [comment]
@Karthik-B-06 Sure
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6547468/87875861-db73aa00-c9dc-11ea-8c1d-44f9a7d246ad.gif)

**Comment by nadav2051** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/6547468/87875908-1aa1fb00-c9dd-11ea-9e3b-a45ac0cf086e.gif)

@Karthik-B-06 sure

**Comment by Karthik-B-06** [comment]
I appreciate it. Thanks for handling this case.
