### ISSUE TITLE
Warning with shadowStyle

### ISSUE THREAD

**Issue by Alex237** [Karthik-B-06/react-native-segmented-control#8]
Hello, i have the following warning when using the component.

Warning: Failed prop type: SegmentedControl: prop type `shadowStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
![image](https://user-images.githubusercontent.com/3592127/90553387-976af500-e194-11ea-86c9-30de97e3310b.png)

```javascript
      <SegmentedControl
        tabs={getTabsLabel()}
        onChange={onChange}
        currentIndex={index}
        activeSegmentBackgroundColor={Colors.primary}
        paddingVertical={8}
        width={initialLayout.width - 16}
        containerStyle={{
          marginVertical: 8,
          marginHorizontal: 8
        }}
        textStyle={{
          fontSize: 12,
          fontFamily: 'RobotoRegular'
        }}
      />
```

**Comment by Karthik-B-06** [comment]
@Alex237 Fixed the warning. Check out the new version. 🎉
